CREATE TABLE DEMIPT.YUPI_REP_FRAUD (	
    EVENT_DT DATE,
	PASSPORT VARCHAR2( 15 BYTE ), 
	FIO VARCHAR2( 300 BYTE ), 
	PHONE VARCHAR2( 20 BYTE ),
    EVENT_TYPE NUMBER( 1 ),
    REPORT_DT DATE
);
CREATE TABLE DEMIPT.YUPI_META_BANK (  
    DBNAME VARCHAR2(30),
	TABLENAME VARCHAR2(30),
	LAST_UPDATE DATE  
);
INSERT INTO DEMIPT.YUPI_META_BANK( DBNAME, TABLENAME, LAST_UPDATE ) 
VALUES ( 'DEMIPT', 'YUPI_DWH_FACT_TRANSACTIONS', to_date( '1890-01-01', 'YYYY-MM-DD' ) );
INSERT INTO DEMIPT.YUPI_META_BANK( DBNAME, TABLENAME, LAST_UPDATE ) 
VALUES ( 'DEMIPT', 'YUPI_DWH_FACT_PSSPRT_BLCKLST', to_date( '1890-01-01', 'YYYY-MM-DD' ) );
INSERT INTO DEMIPT.YUPI_META_BANK( DBNAME, TABLENAME, LAST_UPDATE ) 
VALUES ( 'DEMIPT', 'YUPI_DWH_DIM_CARDS_HIST', to_date( '1890-01-01', 'YYYY-MM-DD' ) );
INSERT INTO DEMIPT.YUPI_META_BANK( DBNAME, TABLENAME, LAST_UPDATE ) 
VALUES ( 'DEMIPT', 'DEMIPT.YUPI_DWH_DIM_ACCNTS_HST', to_date( '1890-01-01', 'YYYY-MM-DD' ) );
INSERT INTO DEMIPT.YUPI_META_BANK( DBNAME, TABLENAME, LAST_UPDATE ) 
VALUES ( 'DEMIPT', 'DEMIPT.YUPI_DWH_DIM_CLNTS_HST', to_date( '1890-01-01', 'YYYY-MM-DD' ) );
INSERT INTO DEMIPT.YUPI_META_BANK( DBNAME, TABLENAME, LAST_UPDATE ) 
VALUES ( 'DEMIPT', 'YUPI_DWH_DIM_TERMINALS_HIST', to_date( '1890-01-01', 'YYYY-MM-DD' ) );

COMMIT
        