CREATE TABLE DEMIPT.YUPI_DWH_FACT_TRANSACTIONS (   
    TRANS_ID VARCHAR2( 20 BYTE ), 
	TRANS_DATE DATE, 
	CARD_NUM CHAR( 20 BYTE ), 
	OPER_TYPE VARCHAR2 ( 20 BYTE ), 
	AMT NUMBER(32,2),
    OPER_RESULT VARCHAR2 ( 20 BYTE ),
    TERMINAL VARCHAR2 (20 BYTE )
);
CREATE TABLE DEMIPT.YUPI_DWH_DIM_TERMINALS_HIST (
    TERMINAL_ID VARCHAR2 (20 BYTE),
    TERMINAL_TYPE CHAR ( 3 BYTE ),
    TERMINAL_CITY VARCHAR2 ( 50 BYTE ),
    TERMINAL_ADDRESS VARCHAR2( 100 BYTE ),
	DELETED_FLG CHAR( 1 BYTE ),
	EFFECTIVE_FROM DATE, 
	EFFECTIVE_TO DATE
);
CREATE TABLE DEMIPT.YUPI_DWH_FACT_PSSPRT_BLCKLST (	 
	PASSPORT_NUM VARCHAR2( 15 BYTE ), 
	ENTRY_DT DATE                                                                                                                                
);
CREATE TABLE DEMIPT.YUPI_DWH_DIM_CARDS_HIST (	
    CARD_NUM CHAR( 20 BYTE ), 
	ACCOUNT_NUM CHAR( 20 BYTE ), 
	DELETED_FLG CHAR( 1 BYTE ),
	EFFECTIVE_FROM DATE, 
	EFFECTIVE_TO DATE
);
CREATE TABLE DEMIPT.YUPI_DWH_DIM_ACCOUNTS_HIST (	
    ACCOUNT CHAR( 20 BYTE ), 
	VALID_TO DATE, 
	CLIENT VARCHAR2( 20 BYTE ), 
	DELETED_FLG CHAR( 1 BYTE ),
	EFFECTIVE_FROM DATE, 
	EFFECTIVE_TO DATE
);
CREATE TABLE DEMIPT.YUPI_DWH_DIM_CLIENTS_HIST (	
    CLIENT_ID VARCHAR2( 20 BYTE ), 
	LAST_NAME VARCHAR2( 100 BYTE ), 
	FIRST_NAME VARCHAR2( 100 BYTE ), 
	PATRONYMIC VARCHAR2( 100 BYTE ),  
	DATE_OF_BIRTH DATE,
    PASSPORT_NUM VARCHAR2( 15 CHAR ),
    PASSPORT_VALID_TO DATE,
    PHONE VARCHAR2( 20 BYTE ), 
	DELETED_FLG CHAR( 1 BYTE ),
	EFFECTIVE_FROM DATE, 
	EFFECTIVE_TO DATE
)


