delete from DEMIPT.YUPI_STG_CARDS;
delete from DEMIPT.YUPI_STG_ACCOUNTS;
delete from DEMIPT.YUPI_STG_CLIENTS;

insert into DEMIPT.YUPI_STG_CARDS( CARD_NUM, ACCOUNT_NUM, CREATE_DT, UPDATE_DT )
select 
	CARD_NUM, ACCOUNT, CREATE_DT, UPDATE_DT
from BANK.CARDS
where coalesce( UPDATE_DT, CREATE_DT ) > (
	select LAST_UPDATE from DEMIPT.YUPI_META_BANK where DBNAME = 'DEMIPT' and TABLENAME = 'YUPI_DWH_DIM_CARDS_HIST'
);
insert into DEMIPT.YUPI_STG_ACCOUNTS( ACCOUNT, VALID_TO, CLIENT, CREATE_DT, UPDATE_DT )
select 
	ACCOUNT, VALID_TO, CLIENT, CREATE_DT, UPDATE_DT
from BANK.ACCOUNTS
where coalesce( UPDATE_DT, CREATE_DT ) > (
	select LAST_UPDATE from DEMIPT.YUPI_META_BANK where DBNAME = 'DEMIPT' and TABLENAME = 'DEMIPT.YUPI_DWH_DIM_ACCNTS_HST'
);
insert into DEMIPT.YUPI_STG_CLIENTS( CLIENT_ID, LAST_NAME, FIRST_NAME, PATRONYMIC,  DATE_OF_BIRTH, PASSPORT_NUM, PASSPORT_VALID_TO, PHONE,CREATE_DT, UPDATE_DT )
select 
	CLIENT_ID, LAST_NAME, FIRST_NAME, PATRONYMIC,  DATE_OF_BIRTH, PASSPORT_NUM, PASSPORT_VALID_TO, PHONE,CREATE_DT, UPDATE_DT
from BANK.CLIENTS
where coalesce( UPDATE_DT, CREATE_DT ) > (
	select LAST_UPDATE from DEMIPT.YUPI_META_BANK where DBNAME = 'DEMIPT' and TABLENAME = 'DEMIPT.YUPI_DWH_DIM_CLNTS_HST'
);

insert into DEMIPT.YUPI_DWH_FACT_TRANSACTIONS( TRANS_ID, TRANS_DATE, CARD_NUM, OPER_TYPE, AMT, OPER_RESULT, TERMINAL )
select
    TRANS_ID, 
    TRANS_DATE, 
    CARD_NUM, 
    OPER_TYPE, 
    AMT,
    OPER_RESULT, 
    TERMINAL
from DEMIPT.YUPI_STG_TRANSACTIONS;

insert into DEMIPT.YUPI_DWH_FACT_PSSPRT_BLCKLST ( PASSPORT_NUM, ENTRY_DT )
select
    PASSPORT_NUM, 
    ENTRY_DT
from DEMIPT.YUPI_STG_PASSPORT_BLACKLIST;

merge into DEMIPT.YUPI_DWH_DIM_TERMINALS_HIST T
using DEMIPT.YUPI_STG_TERMINALS S
on ( T.TERMINAL_ID = S.TERMINAL_ID and T.EFFECTIVE_FROM < coalesce( S.UPDATE_DT, S.CREATE_DT ) )
when matched then update set T.EFFECTIVE_TO = to_date( '2999-12-31', 'YYYY-MM-DD' )
when not matched then insert (TERMINAL_ID, TERMINAL_TYPE, TERMINAL_CITY, TERMINAL_ADDRESS, DELETED_FLG, EFFECTIVE_FROM, EFFECTIVE_TO) 
values (S.TERMINAL_ID, S.TERMINAL_TYPE, S.TERMINAL_CITY, S.TERMINAL_ADDRESS, 'N', coalesce( UPDATE_DT, CREATE_DT ), to_date( '2999-12-31', 'YYYY-MM-DD' ));

insert into DEMIPT.YUPI_DWH_DIM_ACCOUNTS_HIST( ACCOUNT, VALID_TO, CLIENT, DELETED_FLG, EFFECTIVE_FROM, EFFECTIVE_TO )
select
	ACCOUNT,
	VALID_TO,
	CLIENT,
	'N',
	coalesce( UPDATE_DT, CREATE_DT ),
	to_date( '2999-12-31', 'YYYY-MM-DD' )
from DEMIPT.YUPI_STG_ACCOUNTS;
merge into DEMIPT.YUPI_DWH_DIM_ACCOUNTS_HIST T
using DEMIPT.YUPI_STG_ACCOUNTS S
on ( T.ACCOUNT = S.ACCOUNT and T.EFFECTIVE_FROM < coalesce( S.UPDATE_DT, S.CREATE_DT ) )
when matched then update set 
    T.EFFECTIVE_TO = coalesce( S.UPDATE_DT, S.CREATE_DT ) - interval '1' second
		where T.EFFECTIVE_TO = to_date( '2999-12-31', 'YYYY-MM-DD' );

insert into DEMIPT.YUPI_DWH_DIM_CARDS_HIST( CARD_NUM, ACCOUNT_NUM, DELETED_FLG, EFFECTIVE_FROM, EFFECTIVE_TO )
select
	CARD_NUM,
	ACCOUNT_NUM,
	'N',
	coalesce( UPDATE_DT, CREATE_DT ),
	to_date( '2999-12-31', 'YYYY-MM-DD' )
from DEMIPT.YUPI_STG_CARDS;
merge into DEMIPT.YUPI_DWH_DIM_CARDS_HIST T
using DEMIPT.YUPI_STG_CARDS S
on ( T.CARD_NUM = S.CARD_NUM and T.EFFECTIVE_FROM < coalesce( S.UPDATE_DT, S.CREATE_DT ) )
when matched then update set 
    T.EFFECTIVE_TO = coalesce( S.UPDATE_DT, S.CREATE_DT ) - interval '1' second
		where T.EFFECTIVE_TO = to_date( '2999-12-31', 'YYYY-MM-DD' );

insert into DEMIPT.YUPI_DWH_DIM_CLIENTS_HIST( CLIENT_ID, LAST_NAME, FIRST_NAME, PATRONYMIC, DATE_OF_BIRTH, PASSPORT_NUM, PASSPORT_VALID_TO, PHONE, DELETED_FLG, EFFECTIVE_FROM, EFFECTIVE_TO )
select
	CLIENT_ID,
	LAST_NAME,
	FIRST_NAME,
	PATRONYMIC,
	DATE_OF_BIRTH,
	PASSPORT_NUM,
    PASSPORT_VALID_TO,
    PHONE,
    'N',
	coalesce( UPDATE_DT, CREATE_DT ),
	to_date( '2999-12-31', 'YYYY-MM-DD' )	
from DEMIPT.YUPI_STG_CLIENTS;
merge into DEMIPT.YUPI_DWH_DIM_CLIENTS_HIST T
using DEMIPT.YUPI_STG_CLIENTS S
on ( T.CLIENT_ID = S.CLIENT_ID and T.EFFECTIVE_FROM < coalesce( S.UPDATE_DT, S.CREATE_DT ) )
when matched then update set 
    T.EFFECTIVE_TO = coalesce( S.UPDATE_DT, S.CREATE_DT ) - interval '1' second
		where T.EFFECTIVE_TO = to_date( '2999-12-31', 'YYYY-MM-DD' );

update DEMIPT.YUPI_META_BANK 
set LAST_UPDATE = ( select max(TRANS_DATE) from DEMIPT.YUPI_STG_TRANSACTIONS )
where  DBNAME = 'DEMIPT' and TABLENAME = 'YUPI_DWH_FACT_TRANSACTIONS' and (select max(TRANS_DATE) from DEMIPT.YUPI_STG_TRANSACTIONS ) is not null;
update DEMIPT.YUPI_META_BANK 
set LAST_UPDATE = ( select max(ENTRY_DT) from DEMIPT.YUPI_STG_PASSPORT_BLACKLIST )
where  DBNAME = 'DEMIPT' and TABLENAME = 'YUPI_DWH_FACT_PSSPRT_BLCKLST' and (select max(ENTRY_DT) from DEMIPT.YUPI_STG_PASSPORT_BLACKLIST ) is not null;
update DEMIPT.YUPI_META_BANK
set LAST_UPDATE = ( select max( coalesce( UPDATE_DT, CREATE_DT ) ) from DEMIPT.YUPI_STG_CARDS )
where  DBNAME = 'DEMIPT' and TABLENAME = 'YUPI_DWH_DIM_CARDS_HIST' and (select max(coalesce( UPDATE_DT, CREATE_DT )) from DEMIPT.YUPI_STG_CARDS ) is not null;
update DEMIPT.YUPI_META_BANK
set LAST_UPDATE = ( select max( coalesce( UPDATE_DT, CREATE_DT ) ) from DEMIPT.YUPI_STG_ACCOUNTS )
where  DBNAME = 'DEMIPT' and TABLENAME = 'DEMIPT.YUPI_DWH_DIM_ACCNTS_HST' and (select max(coalesce( UPDATE_DT, CREATE_DT )) from DEMIPT.YUPI_STG_ACCOUNTS ) is not null;
update DEMIPT.YUPI_META_BANK
set LAST_UPDATE = ( select max( coalesce( UPDATE_DT, CREATE_DT ) ) from DEMIPT.YUPI_STG_CLIENTS )
where  DBNAME = 'DEMIPT' and TABLENAME = 'DEMIPT.YUPI_DWH_DIM_CLNTS_HST' and (select max(coalesce( UPDATE_DT, CREATE_DT )) from DEMIPT.YUPI_STG_CLIENTS ) is not null;
update DEMIPT.YUPI_META_BANK
set LAST_UPDATE = ( select max( coalesce( UPDATE_DT, CREATE_DT ) ) from DEMIPT.YUPI_STG_TERMINALS )
where  DBNAME = 'DEMIPT' and TABLENAME = 'YUPI_DWH_DIM_TERMINALS_HIST' and (select max(coalesce( UPDATE_DT, CREATE_DT )) from DEMIPT.YUPI_STG_TERMINALS ) is not null;

delete from DEMIPT.YUPI_STG_TRANSACTIONS;
delete from DEMIPT.YUPI_STG_PASSPORT_BLACKLIST;
delete from DEMIPT.YUPI_STG_TERMINALS;

commit
